# Generated by Django 3.2.10 on 2022-11-22 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_api', '0002_auto_20221122_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages_deleted_arcive',
            old_name='receiver',
            new_name='receiver_delete',
        ),
        migrations.RenameField(
            model_name='messages_deleted_arcive',
            old_name='sender',
            new_name='sender_delete',
        ),
    ]
