# Generated by Django 3.2.10 on 2022-11-22 09:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messages_api', '0003_auto_20221122_0814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages_deleted_arcive',
            new_name='Messages_deleted_archive',
        ),
    ]
